const data={
    products: [
        {
            _id:'1',
            name:"Jean Shirt",
            category:"Shirts",
            image:'./images/product-1.jpeg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:"Jeans",
            category:"Pants",
            image:'./images/product-2.jpeg',
            price:30,
            brand:'Johnny Walker',
            rating:4.0,
            numReviews:70,
            description:'high quality product',
        },
        {
            _id:'3',
            name:"Nike Shirt",
            category:"Shirts",
            image:'./images/product-3.jpeg',
            price:69,
            brand:'Nike',
            rating:4.8,
            numReviews:1,
            description:'high quality product',
        },
        {
            _id:'4',
            name:"Hoodies",
            category:"Jackets",
            image:'./images/product-4.jpeg',
            price:120,
            brand:'Nike',
            rating:4.7,
            numReviews:90,
            description:'high quality product',
        },
        {
            _id:'5',
            name:"Sweaters",
            category:"Jackets",
            image:'./images/product-5.jpeg',
            price:420,
            brand:'Addidas',
            rating:3.5,
            numReviews:209,
            description:'high quality product',
        },
        {
            _id:'6',
            name:"Formal 3-piece suit",
            category:"Shirts",
            image:'./images/product-6.jpeg',
            price:20,
            brand:'Brooks Brothers',
            rating:4.9,
            numReviews:100,
            description:'high quality product',
        },
    ],
};
export default data;